### ISSUE TITLE
Script command needed to write into map_warps DB table

### ISSUE THREAD

**Issue by estralis** [Illarion-eV/Illarion-Server#32]
(more details follow)

**Comment by vilarion** [comment]
Has this been tested?

**Comment by estralis** [comment]
> Has this been tested?

Not yet. I have the action  to do so but I didn't find the time yet. Maybe someone else can test it sooner than me.

**Comment by vilarion** [comment]
Since no errors have been reported, I will now assume that this works and put it in the next release.

**Comment by estralis** [comment]
> Since no errors have been reported, I will now assume that this works and put it in the next release.

Sorry it took so long, here is my report: https://illarion.org/community/forums/viewtopic.php?f=14&t=42730

**Comment by estralis** [comment]
All issues resolved.
