### ISSUE TITLE
Monitor script execution times.

### ISSUE THREAD

**Issue by vilarion** [Illarion-eV/Illarion-Server#63]
Log script run times, give warnings when scripts run too long, maybe kill scripts which exceed a maximum if possible.

**Comment by dabates** [comment]
Quick question @vilarion .  Do you have a config for the "max time" .. or "warning time" .. or is this something that will be hard coded?

**Comment by vilarion** [comment]
@dabates I would probably hard-code that in tuningConstants.hpp, below `constexpr auto gameLoopInterval = 100ms;`, since it should probably be lower than that (maybe 10ms?!). Also I would probably just go with a hard limit first, but there could be fancier strategies, too. The number of violations of a script since the last reload would be an interesting metric as well, usable e.g. in the logged warning messages.
