### ISSUE TITLE
Guide?

### ISSUE THREAD

**Issue by robotrono** [Illarion-eV/Illarion-Server#8]
Hi, I want install a server for play with my friends. But I dont know how 
Is there a guide to create a server? I have a server with Ubuntu.

Sorry for my bad english.

**Comment by vilarion** [comment]
Hi!

There is a pre-installed server available within a virtual box vm:
https://spideroak.com/browse/share/vilarion/localserver/localserver/
There you will also find a readme file, explaining how to set it up.

If you want to run the server natively, you could try to use the deb package, which is also used by the virtual box vm:
apt repo: http://illarion.org/repos/apt/debian/
gpg key: http://illarion.org/repos/apt/debian/illarion.gpg.key
That one comes with compiled binary and default config file and sets up the required libs.
However, you still need to get maps, scripts and database on your own.
The update scripts inside the vm should give you a good idea what you need and how to get it,

All things considered, using the out-of-the-box virtual machine is probably the easiest option.
