### ISSUE TITLE
build.yml Build Docker Image fails at Login to Github

### ISSUE THREAD

**Issue by brightrim** [Illarion-eV/Illarion-Server#97]
When attempting to initiate a server build via github actions, it fails to login to Github and docker images are not deployed.
A rebuild like this is necessary to allow adding new items to NPCs due to the server side NPC compiler checks not recognising new items otherwise, thus this puts a halt on development beyond the current housing update and should be considered urgent.

https://github.com/Illarion-eV/Illarion-Server/actions

Related attempts by @Kerruan to fix it: https://github.com/Illarion-eV/Illarion-Server/pull/96

The error:
```
Run docker/login-action@v1
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Logging into ghcr.io...
Error: Error response from daemon: Get "https://ghcr.io/v2/": denied: denied```

**Comment by brightrim** [comment]
I can see the builds are now running without error here on github and my local server now downloaded a new docker image where it was possible to add the new copper handbell item previously added to a vendor meaning the npc compiler has been updated, so this particular issue seems to be resolved.

Thank you @mkaring !

**Comment by mkaring** [comment]
Once a server release is created the next time, `dependabot` will kick into action with checking and maintaining all updates to the github action infrastructure that are required.
